name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (v1.0.0, v1.0.1, etc.)

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: make clean && make
      
      - name: Package binary
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          OS_NAME=$(uname -s | tr '[:upper:]' '[:lower:]')
          if [ "$OS_NAME" = "darwin" ]; then
            PLATFORM="darwin-amd64"
          else
            PLATFORM="linux-amd64"
          fi
          tar -czf sshell-v${VERSION}-${PLATFORM}.tar.gz sshell
      
      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: sshell-v*-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
